### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by koriym** [bearsunday/BEAR.Package#71]
@mackstar san point out but not yet finished.
- [x] va/www/asset/ files
- [-] error page with template engine
- [x] is `autoload.php` ok ?
- [x] nginx configuration

@koriym noticed but not yet finished.
- [x] miniRouter to AuraRouter
- [x] integration $link property and `@Link` annotation
- ~~[ ] _Manual, or Document_~~
- [x] PSR-3 logger (monolog)
- [x] use Aura.Sql
- [x] avoid weaved class error reporting
- [ ] using another app resource sample code

**Comment by MugeSo** [comment]
リストを`[ ] TODO`記法にしたらわかりやすくないですかね。

**Comment by MugeSo** [comment]
nginxの設定は下記で動いてます。
これだと、/var/wwwにindex.phpを配置する必要がありません。

``` nginx
location / {
    root  /path/to/BEAR.Package/apps/Sandbox/var/www;
    try_files
        $uri
        @webapp;
}

location @webapp {
    fastcgi_pass   127.0.0.1:9000;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME /path/to/BEAR.Package/apps/Sandbox/bootstrap/contexts/prod.php;
    include        fastcgi_params;
}
```

ちなみに、実際にはchefのレシピを作っている途中です。

**Comment by koriym** [comment]
It's nice to see `nginx` setting. Thanks @MugeSo Maybe we put it somewhere in BEAR.Package ?

**Comment by MugeSo** [comment]
Of course, sure :smile:
